### ISSUE TITLE
Circular dependency when adding s3 upload event

### ISSUE THREAD

**Issue by aprilmintacpineda** [dsandor/example-aws-s3-lambda#1]
I'm trying to do just as what you have here in this example, I always encounter this error:

```bash
Error: Failed to create changeset for the stack: sls-my-sample-app, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Circular dependency between resources: [forgotPasswordConfirmApiEventPermissionStage, mainBackendApi, changeProfilePictureApiEventPermissionStage, resendEmailCodeApiEventPermissionStage, verifyEmailApiEventPermissionStage, profilePictureUploadedUploadPermission, mainBackendApiDeploymentad50fa5e91, forgotPasswordSendApiEventPermissionStage, changeProfilePicture, loginApiEventPermissionStage, changePersonalInfoApiEventPermissionStage, usersS3Bucket, mainBackendApiStage, profilePictureUploaded, profilePictureUploadedRole, changeProfilePictureRole, registerApiEventPermissionStage]
```

This is what my template looks like:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sls-my-sample-app

  Sample SAM Template for sls-my-sample-app
  
Parameters:
  Stage:
    Description: Required staged of the current build
    Type: String
    Default: dev

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 512
    Timeout: 60
    Runtime: nodejs12.x
    Environment:
      Variables:
        STAGE: !Ref Stage
        USERS_BUCKET: !Ref usersS3Bucket
  Api:
    OpenApiVersion: 3.0.1

Resources:
  register:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/guest/register.handler
      Layers:
        - !Ref dependencies
      Policies:
        - Statement:
          - Action:
              - ses:SendEmail
            Effect: Allow
            Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /register
            RestApiId:
              Ref: mainBackendApi
  forgotPasswordSend:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/guest/forgotPasswordSend.handler
      Layers:
        - !Ref dependencies
      Policies:
        - Statement:
            - Action:
                - ses:SendEmail
              Effect: Allow
              Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /forgot-password-send
            RestApiId:
              Ref: mainBackendApi
  forgotPasswordConfirm:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/guest/forgotPasswordConfirm.handler
      Layers:
        - !Ref dependencies
      Policies:
        - Statement:
            - Action:
                - ses:SendEmail
              Effect: Allow
              Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /forgot-password-confirm
            RestApiId:
              Ref: mainBackendApi
  login:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/guest/login.handler
      Layers:
        - !Ref dependencies
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /login
            RestApiId:
              Ref: mainBackendApi
  verifyEmail:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/auth/verifyEmail.handler
      Layers:
        - !Ref dependencies
      Policies:
        - Statement:
          - Action:
              - ses:SendEmail
            Effect: Allow
            Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /verify-email
            RestApiId:
              Ref: mainBackendApi
  resendEmailCode:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/auth/resendEmailCode.handler
      Layers:
        - !Ref dependencies
      Policies:
        - Statement:
          - Action:
              - ses:SendEmail
            Effect: Allow
            Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /resend-email-code
            RestApiId:
              Ref: mainBackendApi
  changePersonalInfo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/auth/changePersonalInfo.handler
      Layers:
        - !Ref dependencies
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /change-personal-info
            RestApiId:
              Ref: mainBackendApi
  changeProfilePicture:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/auth/changeProfilePicture.handler
      Layers:
        - !Ref dependencies
      Policies:
        - Statement:
          - Action:
              - s3:PutObject
              - s3:PutObjectAcl
            Effect: Allow
            Resource:
              - !Join
                - ""
                - - !GetAtt usersS3Bucket.Arn
                  - "/*.jpg"
              - !Join
                - ""
                - - !GetAtt usersS3Bucket.Arn
                  - "/*.jpeg"
              - !Join
                - ""
                - - !GetAtt usersS3Bucket.Arn
                  - "/*.png"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /change-profile-picture
            RestApiId:
              Ref: mainBackendApi
  profilePictureUploaded:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/events/s3/profilePictureUploaded.handler
      MemorySize: 2048
      Layers:
        - !Ref dependencies
      Policies:
        - Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Join
                - ""
                - - !GetAtt usersS3Bucket.Arn
                  - "/*.jpg"
              - !Join
                - ""
                - - !GetAtt usersS3Bucket.Arn
                  - "/*.jpeg"
              - !Join
                - ""
                - - !GetAtt usersS3Bucket.Arn
                  - "/*.png"
      Events:
        Upload:
          Type: S3
          Properties:
            Bucket: !Ref usersS3Bucket
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: newProfilePicture_
  dependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: src/dependencies
      LayerName: sls-my-sample-app
      RetentionPolicy: Retain
  mainBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
  usersS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - "sls-my-sample-app-users"
          - !Ref Stage
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
            - "*"
          AllowedMethods:
            - GET
            - PUT
            - HEAD
          AllowedOrigins:
            - "*"
      Tags:
        - Key: "what"
          Value: "sls-my-sample-app users s3 bucket"
```

The error is coming from `profilePictureUploaded` function, probably because of the S3 event, can you help me out?
